// <auto-generated />
using HikerPals.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HikerPals.Migrations
{
    [DbContext(typeof(HikerContext))]
    partial class HikerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HikerPals.Models.Hiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnName("Age")
                        .HasColumnType("int");

                    b.Property<int>("AverageDailyMiles")
                        .HasColumnType("int");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.HasIndex("TrailId");

                    b.ToTable("Hikers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 45,
                            AverageDailyMiles = 15,
                            PackId = 1,
                            TrailId = 1,
                            TrailName = "Low Branch",
                            YearsExperience = 15,
                            email = "littleJimmy@aol.com"
                        },
                        new
                        {
                            Id = 2,
                            Age = 65,
                            AverageDailyMiles = 7,
                            PackId = 1,
                            TrailId = 2,
                            TrailName = "Ten Steps",
                            YearsExperience = 30,
                            email = "ten@aol.com"
                        },
                        new
                        {
                            Id = 3,
                            Age = 33,
                            AverageDailyMiles = 4,
                            PackId = 2,
                            TrailId = 3,
                            TrailName = "Coach",
                            YearsExperience = 2,
                            email = "coach@aol.com"
                        },
                        new
                        {
                            Id = 4,
                            Age = 35,
                            AverageDailyMiles = 4,
                            PackId = 3,
                            TrailId = 4,
                            TrailName = "The Captain",
                            YearsExperience = 2,
                            email = "Cap@aol.com"
                        });
                });

            modelBuilder.Entity("HikerPals.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("TrailId");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            Distance = 2190.0,
                            TName = "Appalacian Trail"
                        },
                        new
                        {
                            TrailId = 2,
                            Distance = 2650.0,
                            TName = "Pacific Crest Trail"
                        },
                        new
                        {
                            TrailId = 3,
                            Distance = 789.0,
                            TName = "Arizona Trail"
                        },
                        new
                        {
                            TrailId = 4,
                            Distance = 3100.0,
                            TName = "Continental Divide Trail"
                        });
                });

            modelBuilder.Entity("HikerPals.Models.pack", b =>
                {
                    b.Property<int>("PackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PackName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackVolume")
                        .HasColumnType("int");

                    b.HasKey("PackId");

                    b.ToTable("pack");

                    b.HasData(
                        new
                        {
                            PackId = 1,
                            PackName = "Osprey Atmos",
                            PackVolume = 65
                        },
                        new
                        {
                            PackId = 2,
                            PackName = "Gregory Paragon",
                            PackVolume = 58
                        },
                        new
                        {
                            PackId = 3,
                            PackName = "REI Traverse",
                            PackVolume = 65
                        });
                });

            modelBuilder.Entity("HikerPals.Models.Hiker", b =>
                {
                    b.HasOne("HikerPals.Models.pack", "pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikerPals.Models.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
